
[general]
live_config_reload = true
import = [
   #"~/.config/alacritty/oxocarbon-dark.toml"
   "~/.config/alacritty/everforest_dark.toml"
]

[window]
dimensions = { columns = 80, lines = 24 }
decorations = "full"

[font]
normal = { family = "Maple Mono NL NF CN" }
size = 11.0

