
[general]
live_config_reload = true
import = [
   #"~/.config/alacritty/oxocarbon-dark.toml"
   #"~/.config/alacritty/everforest_dark.toml"
   "~/.config/alacritty/nord.toml"
]

[window]
dimensions = { columns = 80, lines = 24 }
decorations = "full"

[font]
normal = { family = "Liberation Mono" }
size = 13

