
[general]
live_config_reload = true
import = [
   "~/.config/alacritty/gruvbox-dark.toml"
]

[window]
dimensions = { columns = 80, lines = 24 }
decorations = "full"

[font]
normal = { family = "Liberation Mono" }
size = 13

